# Generated by Django 6.0.6 on 2026-06-25 10:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script', models.TextField(help_text='Raw conversation script as submitted by the user.')),
                ('voice_map', models.JSONField(help_text="Mapping of speaker name -> Kokoro voice ID, e.g. {'Host': 'am_adam'}.")),
                ('keep_chunks', models.BooleanField(default=False, help_text='If True, intermediate chunk_*.wav files are preserved on disk.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('audio_file', models.FileField(blank=True, help_text='Final merged MP3 file, populated once status=completed.', null=True, upload_to='outputs/')),
                ('error_message', models.TextField(blank=True, help_text='Populated when status=failed, with a human-readable reason.', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Wall-clock time the generation task took, for monitoring.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='conversatio_status_2e05e4_idx')],
            },
        ),
    ]
